### PR TITLE
Docker files and fixing a spelling mistake

### PR DESCRIPTION
**Pull request by bananasov**
This beautiful but cursed PR adds files needed by docker to build it and of course a docker compose file to use it with compose. Although the dockerfile is pretty cursed, it works.

### CODE REVIEW

**Comment by hugeblank** [comment]
Allegedly there's a way to break out the typescript compilation, and JS running steps. If you could do that that would be great and I'd be down to merge. Also thanks for catching the typo!

**Comment by bananasov** [comment]
> Allegedly there's a way to break out the typescript compilation, and JS running steps. If you could do that that would be great and I'd be down to merge. Also thanks for catching the typo!

yeah shouldn't be too hard to do, on it

**Comment by piprett** [comment]
Thought I would charm in here, with an [example](https://github.com/Erb3/Kristsplit/blob/main/Dockerfile) of how "breaking out" can be done. The last `CMD [ "app.js" ]` in the example should probably be replaced by a `node app.js`, or using a [distroless docker image](https://github.com/GoogleContainerTools/distroless/tree/main/nodejs).
It might also be an idea to use a GitHub action to automatically publish to the GitHub Package Repository, alternatively DockerHub [(Example)](https://github.com/Erb3/Kristsplit/blob/main/.github/workflows/docker-image.yml).

**Comment by fucksophie** [comment]
Recently, netmountcc switched to Bun. This pull request should be switched to use Bun instead.

**Pull request closed without merging**
